- name: Get worker join command
  hosts: manager
  become: true
  gather_facts: false
  tasks:
    - name: Get join command
      ansible.builtin.shell:
        cmd: kubeadm token create --print-join-command
      register: join_command_raw

    - name: Set join command
      ansible.builtin.set_fact:
        join_command: "{{ join_command_raw.stdout_lines[0] }}"


- name: Run join command on worker
  hosts: workers
  become: true
  tasks:
    - name: Join cluster
      ansible.builtin.shell:
        cmd: "{{ hostvars['manager'].join_command }} >> node_joined.txt"
        creates: ~/node_joined.txt
