---
- name: Install k8s tools and environment
  hosts:
    - manager
    - workers
  become: true
  gather_facts: false
  tasks:

    - name: Disable swap for current session
      ansible.builtin.command:
        cmd: 'swapoff -a'
        creates: $HOME/swapoff

    - name: Disable swap permanently, persist reboots
      ansible.builtin.replace:
        path: /etc/fstab
        regexp: '^(\s*)([^#\n]+\s+)(\w+\s+)swap(\s+.*)$'
        replace: '#\1\2\3swap\4'
        backup: true

    - name: Get k8s gpg key
      ansible.builtin.get_url:
        url: 'https://pkgs.k8s.io/core:/stable:/v1.30/deb/Release.key'
        dest: '~/Release.key'
        mode: 'a+r'

    - name: Dearmor k8s key
      ansible.builtin.command:
        cmd: 'gpg -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg --dearmor ~/Release.key'
        creates: '/etc/apt/keyrings/kubernetes-apt-keyring.gpg'

    - name: Add k8s repo to Ubuntu
      ansible.builtin.apt_repository:
        filename: kubernetes
        repo: 'deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.30/deb/ /'

    - name: Clear keys
      ansible.builtin.file:
        path: '~/Release.key'
        state: absent

    - name: Install CRI and k8s tools
      ansible.builtin.apt:
        state: present
        update_cache: true
        name:
          - containerd.io
          - kubelet
          - kubeadm
      register: result
      until: result is not failed
      retries: 5
      delay: 5

    - name: Delete containerd config
      ansible.builtin.file:
        path: '/etc/containerd/config.toml'
        state: absent

    - name: Create default containerd config
      ansible.builtin.shell:
        cmd: 'containerd config default > /etc/containerd/config.toml'
        creates: '/etc/containerd/config.toml'


    - name: Enabe systemd cgrops
      ansible.builtin.replace:
        path: '/etc/containerd/config.toml'
        regexp: 'SystemdCgroup = false'
        replace: 'SystemdCgroup = true'

    - name: Start containerd
      ansible.builtin.service:
        name: containerd
        state: restarted
        enabled: true

    - name: Stop docker
      ansible.builtin.service:
        name: docker
        state: stopped
        enabled: false


- name: Install kubectl to manager
  hosts: manager
  become: true
  gather_facts: false
  tasks:
    - name: Install kubectl
      ansible.builtin.apt:
        state: present
        name: kubectl
        update_cache: true
