---
- name: Install k8s tools and environment
  hosts:
    - manager
    - workers
  become: true
  gather_facts: false
  tasks:

    - name: Disable swap for current session
      ansible.builtin.command:
        cmd: 'swapoff -a'
        creates: $HOME/swapoff

    - name: Disable swap permanently, persist reboots
      ansible.builtin.replace:
        path: /etc/fstab
        regexp: '^(\s*)([^#\n]+\s+)(\w+\s+)swap(\s+.*)$'
        replace: '#\1\2\3swap\4'
        backup: true

    - name: Install CRI and k8s tools
      ansible.builtin.apt:
        state: present
        update_cache: true
        name:
          - containerd.io
          - kubelet
          - kubeadm
      register: result
      until: result is not failed
      retries: 10
      delay: 10

    - name: Delete containerd config
      ansible.builtin.file:
        path: '/etc/containerd/config.toml'
        state: absent

    - name: Create default containerd config
      ansible.builtin.shell:
        cmd: 'containerd config default > /etc/containerd/config.toml'
        creates: '/etc/containerd/config.toml'


    - name: Enabe systemd cgrops
      ansible.builtin.replace:
        path: '/etc/containerd/config.toml'
        regexp: 'SystemdCgroup = false'
        replace: 'SystemdCgroup = true'

    - name: Start containerd
      ansible.builtin.service:
        name: containerd
        state: restarted
        enabled: true

    - name: Stop docker
      ansible.builtin.service:
        name: docker
        state: stopped
        enabled: false


- name: Install kubectl to manager
  hosts: manager
  become: true
  gather_facts: false
  tasks:
    - name: Wait for /var/lib/dpkg/lock-frontend to be released
      ansible.builtin.shell:
        cmd: while lsof /var/lib/dpkg/lock-frontend ; do sleep 10; done;
        creates: wait

    - name: Install kubectl
      ansible.builtin.apt:
        state: present
        name: kubectl
        update_cache: true
      register: result
      until: result is not failed
      retries: 10
      delay: 10
