---
- name: Install docker to all instances
  hosts: all
  become: true
  gather_facts: false
  tasks:
    - name: Install system tools
      ansible.builtin.apt:
        state: present
        update_cache: true
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gpg

    - name: Add Docker gpg key to Ubuntu
      ansible.builtin.get_url:
        url: 'https://download.docker.com/linux/ubuntu/gpg'
        dest: '/etc/apt/keyrings/docker.asc'
        mode: 'a+r'

    - name: Add Docker repo to Ubuntu
      ansible.builtin.apt_repository:
        filename: docker
        repo: 'deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu jammy stable'

    - name: Install CRI and k8s tools
      ansible.builtin.apt:
        state: present
        update_cache: true
        name:
          - docker-ce
