---
- name: Setup srv runner
  hosts: srv
  become: true
  gather_facts: false
  tasks:
    - name: Set user for docker
      ansible.builtin.user:
        name: '{{ ansible_user }}'
        append: true
        groups: docker

    - name: Set mirrors to docker
      ansible.builtin.copy:
        src: '../ansible/files/daemon.json'
        dest: '/etc/docker/daemon.json'
        mode: '0660'

    - name: Restart docker
      ansible.builtin.service:
        name: docker
        state: restarted
        enabled: true


- name: Install GitHub Actions Runner
  hosts: srv
  become: true
  vars:
    github_account: "{{ lookup('env', 'GITHUB_ACCOUNT') }}"
    github_repo: "{{ lookup('env', 'GITHUB_REPO') }}"
  roles:
    - role: monolithprojects.github_actions_runner
